"use strict";
exports.__esModule = true;
var express_1 = require("express");
var commentsController_1 = require("../controller/commentsController");
var auth_1 = require("../middleware/auth");
// const {authenticatedUser} = require("../middleware/index");
// import authenticatedUser from "../middleware/index";
var router = express_1["default"].Router();
router.post('/create-comment', auth_1.auth, commentsController_1.createComment);
router.get('/', auth_1.auth, commentsController_1.fetchComments);
router["delete"]('/:commentId', auth_1.auth, commentsController_1.deleteComment);
exports["default"] = router;
