"use strict";
exports.__esModule = true;
var express_1 = require("express");
var post_1 = require("../controller/post");
var auth_1 = require("../middleware/auth");
var blockAccount_1 = require("../controller/blockAccount");
var router = express_1["default"].Router();
router.post('/create-post', auth_1.auth, post_1.createPost);
router.patch('/block/:id', auth_1.auth, blockAccount_1["default"]);
router.put('/toggle-visibility/:postId', auth_1.auth, post_1.togglePostVisibility);
exports["default"] = router;
