"use strict";
exports.__esModule = true;
var express_1 = require("express");
var register_1 = require("../controller/register");
var registerValidation_1 = require("../utils/registerValidation");
var login_1 = require("../controller/login");
var validator = require("express-joi-validation").createValidator({});
var router = express_1["default"].Router();
router.post('/register', validator.body(registerValidation_1["default"]), register_1.register);
router.post('/verify-user', register_1.verifyOTP);
router.post('/login', login_1.Login);
exports["default"] = router;
