"use strict";
exports.__esModule = true;
exports.USER_SUBJECT = exports.FROM_ADMIN_MAIL = exports.SENDINBLUE_HOST = exports.SENDINBLUE_PASSWORD = exports.SENDINBLUE_USER = void 0;
var dotenv_1 = require("dotenv");
dotenv_1["default"].config();
exports.SENDINBLUE_USER = process.env.SENDINBLUE_USER;
exports.SENDINBLUE_PASSWORD = process.env.SENDINBLUE_PASSWORD;
exports.SENDINBLUE_HOST = process.env.SENDINBLUE_HOST;
exports.FROM_ADMIN_MAIL = process.env.FROM_ADMIN_MAIL;
exports.USER_SUBJECT = process.env.USER_SUBJECT;
